Fix 1784
benmosher/eslint-plugin-import pull request #1985
Opened 2021-02-02 20:07 UTC by lilling

hey! found the bug. here in my or enjoy!

2021-02-02 20:16 UTC, lilling commented
this is my fr pr ever to Github
I'll be glad if you guys can help me understand the failing checks

2021-02-02 20:42 UTC, ljharb requested changes
Congrats! To link the PR with an issue, edit either the OP of the PR, and/or the commit message, to contain a phrase like `Fixes #1784` (or "closes", "resolves", etc - there's a bunch).

The appveyor WSL failures can be ignored, they always fail.

I'm not sure why the webpack resolver tests are failing; I'll look into it.

2021-02-02 20:42 UTC, ljharb commented on tests/src/rules/newline-after-import.js
> +      } ],
```suggestion
      errors: [
        {
          line: 2,
          column: 1,
          message: IMPORT_ERROR_MESSAGE,
        },
      ],
```

2021-02-02 20:42 UTC, ljharb commented on tests/src/rules/newline-after-import.js
> +      output: `// issue 1784\nimport { map } from 'rxjs/operators';\n\n@Component({})\nexport class Test {}`,
```suggestion
      code: `
        // issue 1784
        import { map } from 'rxjs/operators';
        @Component({})
        export class Test {}
      `,
      output: `
        // issue 1784
        import { map } from 'rxjs/operators';
        
        @Component({})
        export class Test {}
      `,
```

2021-02-02 21:02 UTC, ljharb commented
Looks like today's npm 7 promotion caused some tests to break on master. I'll fix those, and then rebase your PR on top of it.

2021-02-07 10:18 UTC, lilling commented
@ljharb do you have any updates?

2021-02-07 14:15 UTC, ljharb commented
@lilling no, I’m afraid not :-/ it’s being tracked in #1986, and you don’t have to do anything else - once that’s done, I’ll rebase this, and we can get it in :-)

2021-02-28 21:36 UTC, ljharb approved these changes

2021-03-01 17:09 UTC, ljharb commented
@lilling i've fixed master, so it looks like these are real failures. Please mark this PR as ready for review once you've figured them out :-)

2021-03-01 18:23 UTC, ljharb commented
I'm seeing a few flaky failures in other PRs, so it might not actually be your branch. Stand by :-)

2021-05-12 14:01 UTC, lilling commented
@ljharb Any updates?

2021-05-12 20:10 UTC, merged

2021-05-14 08:15 UTC, minwe commented
```
ESLint: 7.26.0

TypeError: Cannot read property 'type' of null
Occurred while linting /src/components/Range/index.ts:3
    at isExportNameClass (/node_modules/_eslint-plugin-import@2.23.0@eslint-plugin-import/lib/rules/newline-after-import.js:54:69)
```

2021-05-14 14:56 UTC, ljharb commented
@minwe in general, please file new issues for things like that. This one already is filed as #2056 and #2063.